version: '3'
services:
  mysql:
    build: ./mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./mysql/data:/var/lib/mysql
  php:
    build: ./apache
    ports:
      - '80:80'
    volumes:
      - ../../:/var/www/html
    tty: true
    depends_on:
      - mysql

