version: '3'
services:
  mysql80:
    build: ./mysql
    ports:
      - '3306:3306'
    volumes:   
      - ./mysql/data:/var/lib/mysql
    tty: true
  apache24:
    build: ./apache
    command: systemctl enable httpd
    ports:
      - '80:80'
    volumes:
      - ../../:/var/www/html
    tty: true
    privileged: true
    command: /sbin/init
    depends_on:
      - mysql80

